### ISSUE TITLE
producer: timeout issue

### ISSUE THREAD

**Issue by mickelsonm** [bitly/go-nsq#117]
I am running into a timeout issue with producers.

	2015/02/15 18:38:48 INF    1 (x.x.x.x:14150) connecting to nsqd
	2015/02/15 18:38:49 ERR    1 (x.x.x.x:14150) error connecting to nsqd - dial tcp x.x.x.x:14150: i/o timeout

Let me try and explain my setup:

1) I am running a NSQ cluster on Google Compute Engine using Container Engine. (Configuration is about the same as this setup: https://gist.github.com/smreed/e93fd74765caef99266a. Only thing that I have changed is that I setup loadbalancers for the nsq daemon.)

2) I wrote a helper to handle my producer logic ( See: https://gist.github.com/mickelsonm/8ab51cf6171f6aa3100d) 

3) I set the environment variable to the load balancer: 

	NSQ_DAEMON_HOSTS= x.x.x.x:14150

**Comment by jehiah** [comment]
Can you describe how you've configured load balancing in front of nsqd's TCP port 4150? 

Also a typo in the handler you linked to, it defaults to port `4160` when  `NSQ_DAEMON_HOSTS` is missing, but you probably want `4150`.

**Comment by mickelsonm** [comment]
Best way to think about it is a docker setup. You expose port 14150 on the host side that points to 4150 on the container side. So on my load balancer, I setup a forwarding rule for port 14150, which points to the cluster listening on 14150.

As for the helper, when it is missing...yeah I must have fat-fingered that.

**Comment by mreiferson** [comment]
@mickelsonm it still just looks like a misconfiguration and clients are simply unable to connect (i.e. not a specific `go-nsq` issue).

You should be able to confirm this by just trying to telnet to the port.

**Comment by mickelsonm** [comment]
@mreiferson : I made a little more progress. Not sure how but the port was closed on the firewall, so I opened that back up. Now I am getting an IDENTIFY error:

	2015/02/16 11:08:00 ERR    1 (x.x.x.x:14151) error connecting to nsqd - failed to IDENTIFY - unexpected EOF

**Comment by mreiferson** [comment]
Looks like you're connecting on the wrong port (`14151`), it should be `14150`

**Comment by mickelsonm** [comment]
@mreiferson : That was a mistake on my part, thanks. 

It appears I can write to it now, but am having issues with the nsqadmin tool now. Topic shows up, but when I click on it...it says no producers for the topic, so it must be having trouble finding the lookup or something. I'll see if I can tackle this before posting another issue.

**Comment by jehiah** [comment]
If you look at your nsqadmin logs you'll probably find that the broadcast address as reported by nsqd isn't connectable from nsqadmin.
