### ISSUE TITLE
How to  just consume new messages regardless of old messages??

### ISSUE THREAD

**Issue by sundy-li** [bitly/go-nsq#134]
My server started a conusmer to consume messages, then I stop it for 3 days,  then I start my server again, the old message make no sense to me (cause I use nsq for realtime notification), I just want to consume the new messages, how to solve it without consuming in new channel?

**Comment by jehiah** [comment]
If you want to drop all messages you can use the "Empty Channel" option in nsqadmin, or the matching nsqd API endpoint.

It sounds like you have a hard limit on where after which data is useless for you (might be an hour, or a day or something like that). In that case you can embed a timestamp in your messages and just immediately finish messages that are too old w/o doing any additional processing. If you don't have a timestamp in your messages (which i highly recommend) you can use [`Message.Timestamp`](http://godoc.org/github.com/bitly/go-nsq#Message.Timestamp) exposed by go-nsq.
