### ISSUE TITLE
Using go-nsq, how many TCP connections exist between many consumers(in one process) and the same nsqd(producer)?

### ISSUE THREAD

**Issue by FindNemo** [bitly/go-nsq#135]
Using go-nsq, If I have 100 consumers in the same process(A), they have different topics. One nsqd producer(B) have the topics data update for these consumers, they will get data from the same producer. Now, how many TCP connections will be started between A and B? Wheather consumers will multiplex one TCP to the same producer? Thanks a lot.

**Comment by mreiferson** [comment]
100 connections.

**Comment by FindNemo** [comment]
What a pity. Thank you very much!
