### ISSUE TITLE
Is there any reasons to use go-simplejson rather than built-in json package?

### ISSUE THREAD

**Issue by chzyer** [bitly/go-nsq#136]
Hi, guys.
While I'm reading the source in `api_request.go`, I found that it use "simplejson" package to unmarshal json in the method called `apiRequestNegotiateV1`.

Why not just define a struct and pass a pointer which address to it into `json.Unmarshal`.
I think that may improve the readability of the code and may not affect the performance too much.

**Comment by mreiferson** [comment]
@chzyer you're right, there's no compelling reason to depend on that package.  I would merge a patch that makes those changes.

**Comment by mreiferson** [comment]
see #137
