### ISSUE TITLE
nsq admin does shows no client connect and 0 messages 

### ISSUE THREAD

**Issue by thomasmodeneis** [bitly/go-nsq#141]
Hi,

I have started 2 nsqd, 1nsqlookupd and 1 nsqadmin.
When stopping 2 nsqd and 1 nsqlookupd, and starting up again, the nsqadmin does not seem to recognise or for some other reason he cant see other instances are back up.

It also the same for when stopping  2 nsqd, 1 nsqlookupd and 1 nsqadmin and starting up again, The nsqadmin does not seem to recognise or for some other reason he cant see other instances are back up.

I'm not sure what to do, does anyone knows about something that can be related ?

note: the nsqd instances seem to work just fine, the whole system seem to be functional but nsqadmin does not seem to understand and adapt to the new clients.

Thank you

**Comment by jehiah** [comment]
@thomasmodeneis are you seeing that as a temporary state after restarting instances, or as a permanent state?

**Comment by thomasmodeneis** [comment]
Hi @jehiah 
this seem to be a permanent issue, do you think this is maybe because not stoping nsq gracefully? I'm using pkill to stop processes. 
```
#!/bin/bash
pkill nsqlookupd
pkill nsqd
pkill nsqadmin
```

**Comment by jehiah** [comment]
FYI: `pkill` on it's own sends a `SIGTERM` which is a graceful shutdown (as opposed to `pkill -9 ...`).

So if you are not seeing the expected state in nsqadmin, here's what you can do to help troubleshoot:

- Query nsqlookupd api directly to see if it's returning the expected state for your topic.
- Look in nsqd logs to see if it's having an issue communicating with nsqlookupd to register it's topic and channel metadata. 
- Look in nsqadmin logs to see if it's having an issue communicating with nsqlookupd, or communicating with nsqd. (If for example your box is being starved of resources by other processes/systems you might see timeouts).

**Comment by mreiferson** [comment]
closing this, if there are still problems please open an issue on https://github.com/bitly/nsq
