### ISSUE TITLE
how to connect multiple nsq servers（distributed servers） and produce msg

### ISSUE THREAD

**Issue by chuangyou** [bitly/go-nsq#148]
how to connect multiple nsq servers（distributed servers） and produce msg

**Comment by mreiferson** [comment]
hi @chuangyou - on the producer side it is left as an exercise to the user to load-balance publishing.

Typically topologies will colocate `nsqd` with producing services so they'll just publish locally (and you can scale those "silos" horizontally).  Other topologies group a cluster of `nsqd` behind a load balancer and use HTTP.

Hope this helps!
